Task9
alex-ivankova766/ProjectIntern pull request #9
Opened 2022-10-11 09:15 UTC by alex-ivankova766

2022-10-11 13:11 UTC, tusxxx commented on src/main/kotlin/Task1 (1.1 var 2).kt
> +    var number = readLine().toString().toIntOrNull()
.от toString() тут можно избавиться написав readline()?.toIntOrNull()

2022-10-11 13:14 UTC, tusxxx commented on src/main/kotlin/Task2 (1.2).kt
> +    println("Веедено чисел: $countInt, среднее арифметическое: $arithMean")
.забыла вывести сумму

2022-10-11 13:14 UTC, tusxxx commented on src/main/kotlin/Task2 (1.2).kt
> +    val countInt = count.toInt()
.я бы создавать под это отдельную переменную не стал, если использовал ее один раз

2022-10-11 13:15 UTC, tusxxx commented on src/main/kotlin/Task2 (1.2).kt
> +    var count = 0.0
.зачем количество делать с плавающей точкой?)

2022-10-11 13:15 UTC, tusxxx commented on src/main/kotlin/Task2 (1.2).kt
> +        sum += num.toDouble()
toDouble нужно?

2022-10-11 13:17 UTC, tusxxx commented on src/main/kotlin/Task3 (1.3).kt
> +        if (num < hiddenNumber) println("Мало. Попытайтесь снова.")
.инлайнить плохо :c

2022-10-11 13:21 UTC, tusxxx commented on src/main/kotlin/Task3 (1.3).kt
> +        if (num > hiddenNumber) println("Много. Попытайтесь снова.")
.это же else получается)

2022-10-11 13:34 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var1).kt
> +    for (seqNum in 1..lastIndex) {
.плохое название для переменной в for

2022-10-11 13:34 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var1).kt
> +    for (seqNum in 1..lastIndex) {
for (index in list.indicies

2022-10-11 13:35 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var1).kt
> +    val list: Array<Int> = arrayOf(1, 5, 4, 6, 2)
.переменная названа списком, а в ней массив
.массив != список

2022-10-11 13:37 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var2).kt
> +    while (index != (list.size - 1)) {
list.lastIndex

2022-10-11 13:37 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var3).kt
> +        if (index >= 1 && index <= (list.size - 2) && element > list[index - 1] && element > list[index + 1]) {
.из предыдущих тасок поправки сделай

2022-10-11 13:38 UTC, tusxxx commented on src/main/kotlin/Task6 (2.3 var 1).kt
> +    var minimum = 10000000
.это откуда цифры?)))

2022-10-11 13:41 UTC, tusxxx commented on src/main/kotlin/Task6 (2.3 var 3).kt
> +    val product = list.reduce { prod, element -> prod * element }
.ренейм первой перменной в лямбде, мб и второй

2022-10-11 13:45 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +class arrayNums(val list: Array<Int>) {
.Классы с большой буквы

2022-10-11 13:45 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +class arrayNums(val list: Array<Int>) {
.параметр список или массив

2022-10-11 13:46 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +    fun sumPosNums(): Int {
.ренейм. не бойся названий больше, если они явно улучшат понятийность

2022-10-11 13:46 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +        return resultSum
return list.sum()

2022-10-11 13:46 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +    fun arithMath(): Double {
list.average()

2022-10-11 13:47 UTC, tusxxx commented on src/main/kotlin/Task9 (4.2).kt
> +class arrayNums42(val list: Array<Int>) {
из предыдущей

2022-10-11 13:50 UTC, tusxxx commented on src/main/kotlin/Task9 (4.2).kt
> +    fun minElem(): Int {
можно прям 
fun asdasd() = list.max()

2022-10-11 13:50 UTC, tusxxx commented on src/main/kotlin/Task9 (4.2).kt
> +    fun sumNums(): Int {
.это же свойством должно быть

2022-10-14 06:41 UTC, alex-ivankova766 commented on src/main/kotlin/Task1 (1.1 var 2).kt
> +    var number = readLine().toString().toIntOrNull()
спасибо

2022-10-14 06:41 UTC, alex-ivankova766 commented on src/main/kotlin/Task2 (1.2).kt
> +    println("Веедено чисел: $countInt, среднее арифметическое: $arithMean")
спасибо

2022-10-14 06:42 UTC, alex-ivankova766 commented on src/main/kotlin/Task2 (1.2).kt
> +    val countInt = count.toInt()
при более внимательном погружении, оказывается, что она в принципе не нужна.

2022-10-14 06:42 UTC, alex-ivankova766 commented on src/main/kotlin/Task2 (1.2).kt
> +    var count = 0.0
спасибо

2022-10-14 06:42 UTC, alex-ivankova766 commented on src/main/kotlin/Task2 (1.2).kt
> +        sum += num.toDouble()
спасибо

2022-10-14 06:44 UTC, alex-ivankova766 commented on src/main/kotlin/Task3 (1.3).kt
> +        if (num < hiddenNumber) println("Мало. Попытайтесь снова.")
любой сленг для новичка звучит как абракадабра, суть замечания не ясна, смайл в конце вызывает негативную эмоциональную реакцию. а когда непонятно за что тебе досталась неприятная эмоциональная реакция, она удваивается/утраивается и уходит в рекурсию. расшифровывай, пожалуйста)

2022-10-14 06:44 UTC, alex-ivankova766 commented on src/main/kotlin/Task3 (1.3).kt
> +        if (num > hiddenNumber) println("Много. Попытайтесь снова.")
спасибо

2022-10-14 06:45 UTC, alex-ivankova766 commented on src/main/kotlin/Task5 (2.2 var1).kt
> +    for (seqNum in 1..lastIndex) {
спасибо.
or (index in list.indicies) не подходит, потому что 0 индекс пропускаем. либо заставлять программу каждый раз проверять равен ли текущий индекс нолю, либо написать сразу исходя из условий задачи) чем и занимаюсь)

2022-10-14 06:46 UTC, alex-ivankova766 commented on src/main/kotlin/Task5 (2.2 var1).kt
> +    val list: Array<Int> = arrayOf(1, 5, 4, 6, 2)
списки в котлин я в первую неделю ещё не проходила, но с Андреем поговорила по этому поводу, спасибо

2022-10-14 06:47 UTC, alex-ivankova766 commented on src/main/kotlin/Task5 (2.2 var2).kt
> +    while (index != (list.size - 1)) {
та же история, пока не было ни в теории, ни в статьях, которые читала о массивах, поэтому спасибо, но почему при этом задание не принято отнюдь не ясно)

2022-10-14 06:47 UTC, alex-ivankova766 commented on src/main/kotlin/Task6 (2.3 var 3).kt
> +    val product = list.reduce { prod, element -> prod * element }
чем тебе сокращение от слова произведение не зашло? ))) вроде вполне общепринятое )))

2022-10-14 06:48 UTC, alex-ivankova766 commented on src/main/kotlin/Task8 (4.1).kt
> +class arrayNums(val list: Array<Int>) {
спасибо!

2022-10-14 06:48 UTC, alex-ivankova766 commented on src/main/kotlin/Task8 (4.1).kt
> +    fun sumPosNums(): Int {
вполне норм, сумма положительных чисел

2022-10-14 06:49 UTC, alex-ivankova766 commented on src/main/kotlin/Task8 (4.1).kt
> +        return resultSum
по условию задачи требовалось создать методы, а сумма положительных жлементов и сумма всех элементов это сильно разные вещи

2022-10-14 06:49 UTC, alex-ivankova766 commented on src/main/kotlin/Task8 (4.1).kt
> +    fun arithMath(): Double {
по условию задачи требовалось создать методы

2022-10-14 06:49 UTC, alex-ivankova766 commented on src/main/kotlin/Task9 (4.2).kt
> +    fun minElem(): Int {
спасибо

2022-10-14 06:50 UTC, alex-ivankova766 commented on src/main/kotlin/Task9 (4.2).kt
> +    fun sumNums(): Int {
спасибо

2022-10-14 07:13 UTC, tusxxx commented on src/main/kotlin/Task3 (1.3).kt
> +        if (num < hiddenNumber) println("Мало. Попытайтесь снова.")
inlinить - значит в одну строку код писать
.котлин позволяет инлайнить `if (expression) todo()`
.по хорошему должно быть, как ниже, так читабильнее (особенно заметно на больших проектах разницу)
if (expression) {
todo()
}

2022-10-14 07:14 UTC, tusxxx commented on src/main/kotlin/Task3 (1.3).kt
> +        if (num < hiddenNumber) println("Мало. Попытайтесь снова.")
.да и к моим комментариям можешь относиться полегче, я мирный :)

2022-10-14 07:22 UTC, tusxxx commented on src/main/kotlin/Task6 (2.3 var 3).kt
> +    val product = list.reduce { prod, element -> prod * element }
.избегаем таких сокращений, которые могут ввести другого программиста в ступор
prod(uct/uce) ?
.очень важно изначально выработать правильный нейминг, даже на таких понятных функциях

2022-10-14 07:23 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +        return resultSum
.спасибо!

2022-10-14 07:23 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +        return resultSum
.понял!

2022-10-14 10:33 UTC, tusxxx requested changes

2022-10-14 10:33 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var1).kt
> +    val BEFORE_LAST_INDEX = numbers.size - 2
.мы только у констант делаем нейминг ASD_QWE
.тут же простая переменная

2022-10-14 10:33 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var2).kt
> +    while (index != LAST_INDEX) {
while (index != number.lastIndex) {}

2022-10-14 10:33 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var2).kt
> +    val LAST_INDEX = numbers.size - 1
.не константа

2022-10-14 10:33 UTC, tusxxx commented on src/main/kotlin/Task5 (2.2 var3).kt
> +    val BEFORE_LAST_INDEX = numbers.size - 2
.не константа

2022-10-14 10:33 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +    fun comNums(): Int {
.ну совсем не понятно ж что метод делает
.представь свой класс где то в коде из вне
.читаешь.... читаешь...
.тут `val arrayNums = ArrayNums(arrayOf(1,2,3,4))`
потом `arrayNums.comNums()`
.я бы вообще не понял, что там делается и пришлос лезть внутрь функции, смотреть что она делает

2022-10-14 10:33 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +    fun arityMath(): Double {
fun average() = numbers.average()

2022-10-14 10:33 UTC, tusxxx commented on src/main/kotlin/Task8 (4.1).kt
> +    fun sumPosNums(): Int {
`arrayNums.sumPosNums()`?
.я могу подумать sumPositionNumbers
.в голове диссонанс, что под капотом у функции, суммирует она цифры по позиции или как
.я тебе из горького опыта всё советую же)))

2022-10-14 10:38 UTC, alex-ivankova766 commented on src/main/kotlin/Task5 (2.2 var1).kt
> +    val BEFORE_LAST_INDEX = numbers.size - 2
ок, принято

2022-10-14 10:39 UTC, alex-ivankova766 commented on src/main/kotlin/Task5 (2.2 var2).kt
> +    while (index != LAST_INDEX) {
спс

2022-10-14 10:39 UTC, alex-ivankova766 commented on src/main/kotlin/Task5 (2.2 var2).kt
> +    val LAST_INDEX = numbers.size - 1
ок

2022-10-14 10:39 UTC, alex-ivankova766 commented on src/main/kotlin/Task5 (2.2 var3).kt
> +    val BEFORE_LAST_INDEX = numbers.size - 2
ок

2022-10-14 10:39 UTC, alex-ivankova766 commented on src/main/kotlin/Task8 (4.1).kt
> +    fun comNums(): Int {
ок

2022-10-14 10:40 UTC, alex-ivankova766 commented on src/main/kotlin/Task8 (4.1).kt
> +    fun arityMath(): Double {
да там создать нужно функцию, а не скопировать с базовой, ну)))

2022-10-14 10:41 UTC, alex-ivankova766 commented on src/main/kotlin/Task8 (4.1).kt
> +    fun arityMath(): Double {
мы это с Андреем обсуждали, все первичные базовые задачи идут на создание функций дублирующих встроенные, и только если в тексте задачи задано использовать встроенную, тогда нужно использовать её

2022-10-16 06:04 UTC, tusxxx approved these changes

2022-10-18 10:56 UTC, merged